### PR TITLE
CI : mikrobus greybus update & CI build fixes

### PR DESCRIPTION
**Pull request by vaishnav98**
buildroot issue was probably this:
http://buildroot-busybox.2317881.n4.nabble.com/PATCH-1-1-pkg-cmake-mk-fix-host-ccache-support-for-CMake-3-19-td271371.html
and was fixed after bumping up the version to 2020.11.1

firmware build was failing at the 'installing zephyr
pre-requisites stage' due to trying to fetch a old/non
existent package resulting in 404, adding a sudo apt update
solves the problem.

running gbridge on qemu still fails like https://github.com/jadonk/beagleconnect/pull/37#commitcomment-43564138

### CODE REVIEW

**Comment by vaishnav98** [comment]
mikrobus driver works within buildroot but the click
device drivers are not being probed correctly:
in host /opt/gbridge.sh a hack for continously blinking the
led on the SensorTag/Launchpad is added(this background
transaction happening continously prevents some of the greybus
pm suspend events happening, which might have been the cause
for the kernel panic, with this continous background transfer
the kernel panic is not seen and qemu machine does not crash)

changes were tested using ATUSB, CC1352R SensorTag

Welcome to Buildroot
buildroot login: root
Password:
IFLP=`ifconfig | grep lowpan`
ip link set wpan0 down
iwpan phy phy0 set channel 0 26
iwpan dev wpan0 set pan_id 0xabcd
  ip link add link wpan0 name lowpan0 type lowpan
  ip link set lowpan0 up
ip link set wpan0 up
ip -6 addr add 2001:db8::2/64 dev lowpan0
sleep 1

killall -9 gbridge
sleep 1

sleep 5

gbridge > /dev/null 2&1 &
sleep 5
for i in `seq 1 100000`; do gpioset 0 6=1; gpioset 0 6=0; \
                         sleep 1; done

greybus 1-2.2: GMP VID=0x00000126, PID=0x00000126
greybus 1-2.2: DDBL1 Manufacturer=0x00000126, Product=0x00000126
greybus 1-2.2: excess descriptors in interface manifest
mikrobus:mikrobus_port_gb_register: mikrobus gb_probe , num cports= 3, manifest_size 252
mikrobus:mikrobus_port_gb_register: protocol added 11
mikrobus:mikrobus_port_gb_register: protocol added 3
mikrobus:mikrobus_port_gb_register: protocol added 2
mikrobus:mikrobus_port_register: registering port mikrobus-0
mikrobus_manifest:mikrobus_manifest_attach_device: parsed device 1, driver=bme280, protocol=3, reg=76
mikrobus_manifest:mikrobus_manifest_attach_device: parsed device 2, driver=opt3001, protocol=3, reg=44
mikrobus_manifest:mikrobus_manifest_attach_device: parsed device 3, driver=ams-iaq-core, protocol=3, reg=5a
mikrobus_manifest:mikrobus_manifest_parse:  Greybus Service Sample Application manifest parsed with 3 devices
mikrobus mikrobus-0: registering device : bme280
mikrobus mikrobus-0: registering device : opt3001
mikrobus mikrobus-0: registering device : ams-iaq-core

0-0044  0-005a  0-0076  i2c-0

**Comment by vaishnav98** [comment]
https://github.com/jadonk/beagleconnect/issues/48
https://github.com/jadonk/beagleconnect/issues/40

**Review by jadonk — APPROVED** [review]
Looks good. I probably should have updated the individual projects first, but I don't see you changing the indexes here.

**Comment by jadonk** [comment]
> 
> 
> mikrobus driver works within buildroot but the click
> device drivers are not being probed correctly:
> in host /opt/gbridge.sh a hack for continously blinking the
> led on the SensorTag/Launchpad is added(this background
> transaction happening continously prevents some of the greybus
> pm suspend events happening, which might have been the cause
> for the kernel panic, with this continous background transfer
> the kernel panic is not seen and qemu machine does not crash)
> 
> changes were tested using ATUSB, CC1352R SensorTag
> 
> ```
> Welcome to Buildroot
> buildroot login: root
> Password:
> IFLP=`ifconfig | grep lowpan`
> ip link set wpan0 down
> iwpan phy phy0 set channel 0 26
> iwpan dev wpan0 set pan_id 0xabcd
>   ip link add link wpan0 name lowpan0 type lowpan
>   ip link set lowpan0 up
> ip link set wpan0 up
> ip -6 addr add 2001:db8::2/64 dev lowpan0
> sleep 1
> 
> killall -9 gbridge
> sleep 1
> 
> sleep 5
> 
> gbridge > /dev/null 2&1 &
> sleep 5
> for i in `seq 1 100000`; do gpioset 0 6=1; gpioset 0 6=0; \
>                          sleep 1; done
> 
> greybus 1-2.2: GMP VID=0x00000126, PID=0x00000126
> greybus 1-2.2: DDBL1 Manufacturer=0x00000126, Product=0x00000126
> greybus 1-2.2: excess descriptors in interface manifest
> mikrobus:mikrobus_port_gb_register: mikrobus gb_probe , num cports= 3, manifest_size 252
> mikrobus:mikrobus_port_gb_register: protocol added 11
> mikrobus:mikrobus_port_gb_register: protocol added 3
> mikrobus:mikrobus_port_gb_register: protocol added 2
> mikrobus:mikrobus_port_register: registering port mikrobus-0
> mikrobus_manifest:mikrobus_manifest_attach_device: parsed device 1, driver=bme280, protocol=3, reg=76
> mikrobus_manifest:mikrobus_manifest_attach_device: parsed device 2, driver=opt3001, protocol=3, reg=44
> mikrobus_manifest:mikrobus_manifest_attach_device: parsed device 3, driver=ams-iaq-core, protocol=3, reg=5a
> mikrobus_manifest:mikrobus_manifest_parse:  Greybus Service Sample Application manifest parsed with 3 devices
> mikrobus mikrobus-0: registering device : bme280
> mikrobus mikrobus-0: registering device : opt3001
> mikrobus mikrobus-0: registering device : ams-iaq-core
> 
> 0-0044  0-005a  0-0076  i2c-0
> ```

Let's put these into a shell script to run by default.

**Comment by jadonk** [comment]
Let's merge and fix.

**Pull request merged**
